# See https://docs.redoc.ly/cli/configuration/ for more information.
apis:
  main:
    root: "openapi/openapi.yaml"
extends:
  - recommended
rules:
  no-empty-servers: off
features.openapi:
  showConsole: true
  pagination: section
  layout: three-panel
  routingStrategy: browser
