openapi: 3.0.3
info:
  version: 1.0.0
  title: Vality API Keys Management API
  description:
    $ref: './docs/api.md'
  termsOfService: 'https://vality.dev/'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - bearer: []
tags:
  - name: apiKeys
    x-displayName: API-ключи
  - name: errorCodes
    x-displayName: Коды ошибок
    description:
      $ref: './docs/errors.md'
paths:
  /orgs/{partyId}/api-keys:
    $ref: ./paths/apiKeys.yaml
  /orgs/{partyId}/api-keys/{apiKeyId}:
    $ref: ./paths/apiKey.yaml
  /orgs/{partyId}/api-keys/{apiKeyId}/status:
    $ref: ./paths/apiKeyStatus.yaml
components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
